"""Audit generated documents against case evidence — OpenAI primary."""

from __future__ import annotations

import json
import logging
from typing import Any

from bedrock_llm import parse_json_object
from gateway import GATEWAY_MODEL, GatewayMetadata, chat

logger = logging.getLogger("document_auditor")

AUDIT_PROMPT = """\
You are auditing a legal document generated by an AI intake system.
Review the document against the source case state and parsed evidence.
Flag any factual claims in the document that are NOT directly supported by the
case state, parsed documents, or retrieved law/comparables.

Return JSON only:
{
  "audit_status": "verified" | "flagged",
  "flagged_claims": [{"claim": string, "severity": "low"|"medium"|"high", "suggested_fix": string}],
  "confidence": 0-100
}

Use audit_status "verified" when no medium/high severity flags exist."""


async def audit_document(
    *,
    doc_type: str,
    markdown: str,
    case_data: dict[str, Any],
    case_id: str,
    caller_id: str,
) -> dict[str, Any]:
    payload = {
        "doc_type": doc_type,
        "document": markdown[:12000],
        "case_state": {
            k: v
            for k, v in case_data.items()
            if k not in {"transcript_lines", "generated_documents"}
        },
        "parsed_documents": case_data.get("documents") or {},
    }
    messages = [
        {"role": "system", "content": AUDIT_PROMPT},
        {
            "role": "user",
            "content": json.dumps(payload, default=str, ensure_ascii=False),
        },
    ]

    raw = ""
    try:
        # Always route through the gateway: it owns provider selection + failover
        # AND redacts PII (parsed police reports / ER discharges are PII-dense)
        # before any provider sees it, then un-redacts the reply.
        response = await chat(
            GATEWAY_MODEL,
            messages,
            temperature=0.1,
            metadata=GatewayMetadata(case_id=case_id, caller_id=caller_id),
            allow_failover=True,
            timeout_s=30,
        )
        raw = response.content
    except Exception:
        logger.exception("Document audit LLM failed for %s", doc_type)
        return {"audit_status": "pending", "confidence": 0, "flagged_claims": []}

    parsed = parse_json_object(raw) or {}
    flagged = parsed.get("flagged_claims") or []
    status = str(parsed.get("audit_status") or "pending")
    if status != "verified":
        if any(
            str(f.get("severity", "")).lower() in {"medium", "high"}
            for f in flagged
            if isinstance(f, dict)
        ):
            status = "flagged"
        elif not flagged:
            status = "verified"

    return {
        "audit_status": status,
        "flagged_claims": flagged,
        "confidence": int(parsed.get("confidence") or 0),
    }
